# Generated by Django 3.1.1 on 2020-11-30 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.DateField(auto_now=True)),
                ('estock', models.CharField(max_length=20)),
                ('eentryprise', models.CharField(max_length=100)),
                ('equantity', models.CharField(max_length=100)),
                ('eplntgt1', models.IntegerField()),
                ('eplntgt2', models.IntegerField()),
                ('eplntgt3', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='RegisteredAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ads',
            },
        ),
        migrations.CreateModel(
            name='RegisteredForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('verify', models.BooleanField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('edate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Call', models.CharField(default='', max_length=30)),
                ('Timee', models.CharField(default='', max_length=20)),
                ('Script', models.CharField(default='', max_length=30)),
                ('Price', models.CharField(default='', max_length=30)),
                ('TGT1_PTS', models.CharField(default='', max_length=30)),
                ('TGT2_PTS', models.CharField(default='', max_length=30)),
                ('TGT3_PTS', models.CharField(default='', max_length=30)),
                ('LTP', models.CharField(default='', max_length=30)),
                ('SL', models.CharField(default='', max_length=10)),
                ('Remarks', models.CharField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('ShowToUsers', models.BooleanField(default=False)),
                ('TGT1', models.BooleanField(default=True)),
                ('TGT2', models.BooleanField(default=True)),
                ('TGT3', models.BooleanField(default=True)),
                ('SL_Flag', models.BooleanField(default=True)),
            ],
        ),
    ]
